name: Compile What's New

on:
  push:
    branches:
      - main

jobs:
  compile-whatsnew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate What's New page
        run: node .github/scripts/generate-whatsnew.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/whatsnew.html
          git diff --quiet || git commit -m "Automated update of What's New page"
          git push
